'use client';

import { AuditResult } from '@/types/audit';
import { Button } from '@/components/ui/button';
import { downloadTextFile } from '@/lib/utils/file-helpers';

interface ExportButtonProps {
  result: AuditResult;
  fileName: string;
}

export function ExportButton({ result, fileName }: ExportButtonProps) {
  const exportJSON = () => {
    const content = JSON.stringify(result, null, 2);
    downloadTextFile(content, `${fileName}-audit-report.json`, 'application/json');
  };

  const exportHTML = () => {
    const html = generateHTMLReport(result, fileName);
    downloadTextFile(html, `${fileName}-audit-report.html`, 'text/html');
  };

  return (
    <div className="flex gap-2">
      <Button variant="outline" size="sm" onClick={exportJSON}>
        Export JSON
      </Button>
      <Button variant="outline" size="sm" onClick={exportHTML}>
        Export HTML
      </Button>
    </div>
  );
}

function generateHTMLReport(result: AuditResult, fileName: string): string {
  const severityColor = (s: string) => {
    switch(s) { case 'critical': return '#dc2626'; case 'major': return '#ea580c'; default: return '#ca8a04'; }
  };
  return `<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Accessibility Audit Report - ${fileName}</title>
<style>
  body { font-family: system-ui, sans-serif; max-width: 800px; margin: 0 auto; padding: 2rem; color: #1a1a1a; }
  h1 { border-bottom: 2px solid #e5e7eb; padding-bottom: 0.5rem; }
  .score { font-size: 3rem; font-weight: bold; color: ${result.complianceScore >= 85 ? '#16a34a' : result.complianceScore >= 50 ? '#d97706' : '#dc2626'}; }
  .summary { display: flex; gap: 1rem; margin: 1rem 0; }
  .summary span { padding: 0.25rem 0.75rem; border-radius: 9999px; font-size: 0.875rem; font-weight: 600; }
  .issue { border: 1px solid #e5e7eb; border-radius: 8px; padding: 1rem; margin: 0.5rem 0; }
  .severity { display: inline-block; padding: 0.125rem 0.5rem; border-radius: 9999px; font-size: 0.75rem; font-weight: 600; color: white; }
  .rec { background: #f3f4f6; padding: 0.5rem; border-radius: 4px; font-size: 0.875rem; margin-top: 0.5rem; }
</style></head>
<body>
<h1>Accessibility Audit Report</h1>
<p>File: <strong>${fileName}</strong></p>
<p>Date: ${new Date(result.timestamp).toLocaleDateString()}</p>
<div class="score">${result.complianceScore}%</div>
<p>WCAG 2.1 AA Compliance Score</p>
<div class="summary">
  <span style="background:#fecaca;color:#991b1b">${result.criticalCount} Critical</span>
  <span style="background:#fed7aa;color:#9a3412">${result.majorCount} Major</span>
  <span style="background:#fef08a;color:#854d0e">${result.minorCount} Minor</span>
</div>
<h2>Issues (${result.totalIssues})</h2>
${result.findings.map(f => `<div class="issue">
  <span class="severity" style="background:${severityColor(f.severity)}">${f.severity.toUpperCase()}</span>
  <strong>${f.ruleId}</strong> — ${f.wcagCriterion}<br>
  <p>${f.description}</p>
  <small>Page ${f.location.pageNumber}${f.location.elementType ? ` · ${f.location.elementType}` : ''}</small>
  <div class="rec"><strong>Recommendation:</strong> ${f.recommendation}</div>
</div>`).join('\n')}
<hr><p><small>Generated by AccessiblePDF Remediation Tool</small></p>
</body></html>`;
}
