/// <reference lib="webworker" />

import { PDFDocument, PDFPage, PDFFont, StandardFonts, rgb, PDFName, PDFString, PDFArray, PDFDict, PDFNumber, PDFHexString } from 'pdf-lib';

const ctx = self as unknown as DedicatedWorkerGlobalScope;

interface RemediateRequest {
  type: 'REMEDIATE_PDF';
  fileId: string;
  parsedData: any;
  options: {
    language: string;
    title?: string;
  };
}

// Font mapping logic (inline to avoid import issues)
function getStandardFont(fontFamily: string, fontName: string, isBold: boolean, isItalic: boolean): StandardFonts {
  const lower = (fontFamily + ' ' + fontName).toLowerCase();

  let base: StandardFonts, bold: StandardFonts, italic: StandardFonts, boldItalic: StandardFonts;

  if (lower.includes('courier') || lower.includes('mono')) {
    base = StandardFonts.Courier;
    bold = StandardFonts.CourierBold;
    italic = StandardFonts.CourierOblique;
    boldItalic = StandardFonts.CourierBoldOblique;
  } else if (lower.includes('times') || lower.includes('serif') || lower.includes('georgia')) {
    base = StandardFonts.TimesRoman;
    bold = StandardFonts.TimesRomanBold;
    italic = StandardFonts.TimesRomanItalic;
    boldItalic = StandardFonts.TimesRomanBoldItalic;
  } else {
    base = StandardFonts.Helvetica;
    bold = StandardFonts.HelveticaBold;
    italic = StandardFonts.HelveticaOblique;
    boldItalic = StandardFonts.HelveticaBoldOblique;
  }

  if (isBold && isItalic) return boldItalic;
  if (isBold) return bold;
  if (isItalic) return italic;
  return base;
}

ctx.addEventListener('message', async (event: MessageEvent<RemediateRequest>) => {
  const { type, fileId, parsedData, options } = event.data;

  if (type !== 'REMEDIATE_PDF') return;

  try {
    ctx.postMessage({ type: 'REMEDIATE_PROGRESS', fileId, progress: 5, message: 'Creating new PDF document...' });

    const doc = await PDFDocument.create();
    const language = options.language || 'en-US';

    // Determine title
    const title = options.title || parsedData.metadata?.title || 'Untitled Document';

    // Set metadata
    doc.setTitle(title);
    doc.setAuthor('AccessiblePDF Remediation');
    doc.setSubject('Accessible PDF generated by AccessiblePDF');
    doc.setCreator('AccessiblePDF Remediation Tool');
    doc.setProducer('pdf-lib + AccessiblePDF');
    doc.setCreationDate(new Date());
    doc.setModificationDate(new Date());

    // Set catalog properties
    const catalog = doc.catalog;
    catalog.set(PDFName.of('Lang'), PDFString.of(language));
    catalog.set(PDFName.of('MarkInfo'), doc.context.obj({ Marked: true }));
    catalog.set(PDFName.of('ViewerPreferences'), doc.context.obj({ DisplayDocTitle: true }));

    ctx.postMessage({ type: 'REMEDIATE_PROGRESS', fileId, progress: 10, message: 'Embedding fonts...' });

    // Embed all standard fonts
    const fonts = new Map<string, PDFFont>();
    for (const fontName of Object.values(StandardFonts)) {
      fonts.set(fontName, await doc.embedFont(fontName));
    }

    ctx.postMessage({ type: 'REMEDIATE_PROGRESS', fileId, progress: 15, message: 'Creating pages...' });

    const pages = parsedData.pages || [];
    const pdfPages: PDFPage[] = [];

    for (const srcPage of pages) {
      const page = doc.addPage([srcPage.width || 612, srcPage.height || 792]);
      page.node.set(PDFName.of('Tabs'), PDFName.of('S'));
      pdfPages.push(page);
    }

    ctx.postMessage({ type: 'REMEDIATE_PROGRESS', fileId, progress: 20, message: 'Rendering content...' });

    // Render text content
    for (let i = 0; i < pages.length; i++) {
      const srcPage = pages[i];
      const destPage = pdfPages[i];

      const pct = 20 + (i / pages.length) * 50;
      ctx.postMessage({ type: 'REMEDIATE_PROGRESS', fileId, progress: pct, message: `Rendering page ${i + 1} of ${pages.length}...` });

      // Draw text
      for (const item of srcPage.textItems || []) {
        if (!item.text?.trim()) continue;

        try {
          const stdFont = getStandardFont(
            item.fontFamily || 'sans-serif',
            item.fontName || '',
            item.isBold || false,
            item.isItalic || false
          );
          const font = fonts.get(stdFont);
          if (!font) continue;

          const fontSize = Math.max(1, Math.min(item.fontSize || 12, 200));
          let text = item.text;

          try {
            font.encodeText(text);
          } catch {
            text = text.replace(/[^\x20-\x7E]/g, ' ');
            try {
              font.encodeText(text);
            } catch {
              continue;
            }
          }

          const color = item.color || { r: 0, g: 0, b: 0 };
          destPage.drawText(text, {
            x: item.x || 0,
            y: item.y || 0,
            size: fontSize,
            font,
            color: rgb(color.r / 255, color.g / 255, color.b / 255),
          });
        } catch {
          continue;
        }
      }

      // Draw images
      for (const img of srcPage.imageItems || []) {
        try {
          let embedded;
          if (img.mimeType === 'image/jpeg') {
            embedded = await doc.embedJpg(img.data);
          } else {
            embedded = await doc.embedPng(img.data);
          }
          destPage.drawImage(embedded, {
            x: img.x || 0,
            y: img.y || 0,
            width: img.displayWidth || img.width,
            height: img.displayHeight || img.height,
          });
        } catch {
          continue;
        }
      }
    }

    ctx.postMessage({ type: 'REMEDIATE_PROGRESS', fileId, progress: 75, message: 'Adding structure tags...' });

    // Add structure tree (basic)
    try {
      const structTreeRoot = doc.context.obj({
        Type: 'StructTreeRoot',
        K: [],
        ParentTree: { Type: 'NumberTree', Nums: [] },
      });
      const structTreeRootRef = doc.context.register(structTreeRoot);
      catalog.set(PDFName.of('StructTreeRoot'), structTreeRootRef);
    } catch {}

    ctx.postMessage({ type: 'REMEDIATE_PROGRESS', fileId, progress: 85, message: 'Adding bookmarks...' });

    // Add bookmarks from detected headings
    // Simple heuristic: look for text items that appear to be headings
    try {
      const headingItems: { text: string; pageIndex: number; fontSize: number }[] = [];

      // Find body font size
      const allSizes: number[] = [];
      for (const page of pages) {
        for (const item of page.textItems || []) {
          if (item.text?.trim()) allSizes.push(item.fontSize || 12);
        }
      }
      allSizes.sort((a: number, b: number) => a - b);
      const bodySize = allSizes.length > 0 ? allSizes[Math.floor(allSizes.length / 2)] : 12;

      for (const page of pages) {
        for (const item of page.textItems || []) {
          if (!item.text?.trim()) continue;
          const size = item.fontSize || 12;
          if (size > bodySize * 1.2 && item.text.length < 150) {
            headingItems.push({
              text: item.text.trim(),
              pageIndex: page.pageIndex,
              fontSize: size,
            });
          }
        }
      }

      // Deduplicate by combining items that are near each other
      const uniqueHeadings: typeof headingItems = [];
      for (const h of headingItems) {
        const last = uniqueHeadings[uniqueHeadings.length - 1];
        if (last && last.pageIndex === h.pageIndex && Math.abs(last.fontSize - h.fontSize) < 1) {
          last.text += ' ' + h.text;
        } else {
          uniqueHeadings.push({ ...h });
        }
      }

      if (uniqueHeadings.length > 0 && pdfPages.length > 0) {
        const outlineItemRefs: any[] = [];

        for (const heading of uniqueHeadings) {
          const pageIdx = Math.min(heading.pageIndex, pdfPages.length - 1);
          const pageRef = pdfPages[pageIdx].ref;

          let titleStr;
          try {
            titleStr = PDFHexString.fromText(heading.text);
          } catch {
            titleStr = PDFHexString.fromText('Section');
          }

          const outlineItem = doc.context.obj({
            Title: titleStr,
            Dest: [pageRef, 'Fit'],
          });
          outlineItemRefs.push(doc.context.register(outlineItem));
        }

        // Link items
        for (let i = 0; i < outlineItemRefs.length; i++) {
          const item = doc.context.lookup(outlineItemRefs[i]) as PDFDict;
          if (i > 0) item.set(PDFName.of('Prev'), outlineItemRefs[i - 1]);
          if (i < outlineItemRefs.length - 1) item.set(PDFName.of('Next'), outlineItemRefs[i + 1]);
        }

        const outline = doc.context.obj({
          Type: 'Outlines',
          First: outlineItemRefs[0],
          Last: outlineItemRefs[outlineItemRefs.length - 1],
          Count: PDFNumber.of(outlineItemRefs.length),
        });
        const outlineRef = doc.context.register(outline);

        for (const ref of outlineItemRefs) {
          const item = doc.context.lookup(ref) as PDFDict;
          item.set(PDFName.of('Parent'), outlineRef);
        }

        catalog.set(PDFName.of('Outlines'), outlineRef);
        catalog.set(PDFName.of('PageMode'), PDFName.of('UseOutlines'));
      }
    } catch {}

    ctx.postMessage({ type: 'REMEDIATE_PROGRESS', fileId, progress: 95, message: 'Saving PDF...' });

    const pdfBytes = await doc.save();

    ctx.postMessage({ type: 'REMEDIATE_PROGRESS', fileId, progress: 100, message: 'Remediation complete' });

    // Transfer the buffer
    const buffer = pdfBytes.buffer;
    ctx.postMessage(
      { type: 'REMEDIATE_COMPLETE', fileId, pdfBytes: buffer },
      [buffer] as any
    );

  } catch (err: any) {
    ctx.postMessage({
      type: 'REMEDIATE_ERROR',
      fileId,
      error: err.message || 'Unknown remediation error',
    });
  }
});
